<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'plate_number' => 'ABC-1234',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2023,
                'color' => 'Silver',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 75.00,
                'weekly_rate' => 450.00,
                'monthly_rate' => 1800.00,
                'mileage' => 15000,
                'status' => 'available',
                'description' => 'Comfortable sedan perfect for daily commuting and business trips.',
                'features' => ['Bluetooth', 'Backup Camera', 'Cruise Control', 'Air Conditioning'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'XYZ-5678',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2022,
                'color' => 'Blue',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 85.00,
                'weekly_rate' => 510.00,
                'monthly_rate' => 2040.00,
                'mileage' => 22000,
                'status' => 'available',
                'description' => 'Spacious SUV ideal for family trips and outdoor adventures.',
                'features' => ['All-Wheel Drive', 'Bluetooth', 'Backup Camera', 'Roof Rails'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'DEF-9012',
                'make' => 'BMW',
                'model' => '3 Series',
                'year' => 2023,
                'color' => 'Black',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 120.00,
                'weekly_rate' => 720.00,
                'monthly_rate' => 2880.00,
                'mileage' => 8000,
                'status' => 'available',
                'description' => 'Luxury sedan with premium features and excellent performance.',
                'features' => ['Leather Seats', 'Navigation', 'Premium Sound', 'Sport Mode'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'GHI-3456',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'color' => 'White',
                'fuel_type' => 'electric',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 150.00,
                'weekly_rate' => 900.00,
                'monthly_rate' => 3600.00,
                'mileage' => 12000,
                'status' => 'available',
                'description' => 'Electric vehicle with advanced technology and zero emissions.',
                'features' => ['Autopilot', 'Supercharging', 'Glass Roof', 'Minimalist Interior'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'JKL-7890',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2022,
                'color' => 'Red',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 6,
                'daily_rate' => 100.00,
                'weekly_rate' => 600.00,
                'monthly_rate' => 2400.00,
                'mileage' => 18000,
                'status' => 'available',
                'description' => 'Powerful pickup truck perfect for work and heavy hauling.',
                'features' => ['Towing Package', 'Bed Liner', '4x4', 'Bluetooth'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'MNO-2345',
                'make' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'year' => 2023,
                'color' => 'Silver',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 130.00,
                'weekly_rate' => 780.00,
                'monthly_rate' => 3120.00,
                'mileage' => 10000,
                'status' => 'available',
                'description' => 'Elegant luxury sedan with sophisticated design and comfort.',
                'features' => ['Leather Interior', 'Premium Audio', 'LED Lighting', 'Driver Assistance'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'PQR-6789',
                'make' => 'Audi',
                'model' => 'A4',
                'year' => 2022,
                'color' => 'Gray',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 110.00,
                'weekly_rate' => 660.00,
                'monthly_rate' => 2640.00,
                'mileage' => 16000,
                'status' => 'available',
                'description' => 'Sporty sedan with quattro all-wheel drive and premium features.',
                'features' => ['Quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen Audio', 'Sport Suspension'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'STU-0123',
                'make' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2023,
                'color' => 'Green',
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'seats' => 5,
                'daily_rate' => 90.00,
                'weekly_rate' => 540.00,
                'monthly_rate' => 2160.00,
                'mileage' => 14000,
                'status' => 'available',
                'description' => 'Hybrid SUV with excellent fuel efficiency and modern design.',
                'features' => ['Hybrid Engine', 'SmartSense', 'Wireless Charging', 'Panoramic Sunroof'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'VWX-4567',
                'make' => 'Porsche',
                'model' => '911',
                'year' => 2023,
                'color' => 'Yellow',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 4,
                'daily_rate' => 300.00,
                'weekly_rate' => 1800.00,
                'monthly_rate' => 7200.00,
                'mileage' => 5000,
                'status' => 'available',
                'description' => 'Iconic sports car with legendary performance and handling.',
                'features' => ['Sport Chrono Package', 'PASM', 'Porsche Communication Management', 'Sport Exhaust'],
                'is_available' => true,
            ],
            [
                'plate_number' => 'YZA-8901',
                'make' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2022,
                'color' => 'White',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 5,
                'daily_rate' => 65.00,
                'weekly_rate' => 390.00,
                'monthly_rate' => 1560.00,
                'mileage' => 20000,
                'status' => 'available',
                'description' => 'Compact hatchback perfect for city driving and daily use.',
                'features' => ['Bluetooth', 'Backup Camera', 'Cruise Control', 'Apple CarPlay'],
                'is_available' => true,
            ],
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
